version: '3'
services:

  postgresql:
    image: postgres:12.5
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sent 
      POSTGRES_PASSWORD: sent 
      POSTGRES_DB: sent 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: unless-stopped 
